# Reworking dataset for data visualization - World Energy Consumption

Using standard and pandas libraries preprocessing data for visualization using Tableau.

Original dataset by [Our World in Data](https://ourworldindata.org/energy)

[GitGub repository](https://github.com/owid/energy-data)

## Import needed libriaries

In [2]:
import pandas as pd
import requests
import io

## Get data from repository

Copy the url as the raw version of the file on GitHub with data `owid-energy-data.csv`.

In [3]:
url ='https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-data.csv'

In [4]:
download = requests.get(url).content

In [5]:
df = pd.read_csv(io.StringIO(download.decode('utf-8')))

In [6]:
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,Afghanistan,1900,AFG,4832414.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,1901,AFG,4879685.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afghanistan,1902,AFG,4935122.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afghanistan,1903,AFG,4998861.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afghanistan,1904,AFG,5063419.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Copy the url as the raw version of the file on GitHub with codebook `owid-energy-codebook`.

In [7]:
url_codebook ='https://raw.githubusercontent.com/owid/energy-data/master/owid-energy-codebook.csv'

In [8]:
download_codebook = requests.get(url_codebook).content

In [9]:
df_codebook = pd.read_csv(io.StringIO(download_codebook.decode('utf-8')))

In [10]:
df_codebook

,column,description,source
0,country,Geographic location,Our World in Data
1,year,Year of observation,Our World in Data
2,iso_code,ISO 3166-1 alpha-3 three-letter country codes,International Organization for Standardization
3,population,Population,Calculated by Our World in Data based on diffe...
4,gdp,"Total real gross domestic product, inflation-a...",Maddison Project Database
...,...,...,...
123,wind_elec_per_capita,"Per capita electricity generation from wind, m...",Calculated by Our World in Data based on BP St...
124,wind_electricity,"Electricity generation from wind, measured in ...",Calculated by Our World in Data based on BP St...
125,wind_energy_per_capita,Per capita primary energy consumption from win...,Calculated by Our World in Data based on BP St...
126,wind_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
127,wind_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...

In [11]:
pd.set_option('display.max_rows', 130)

In [12]:
df_codebook

,column,description,source
0,country,Geographic location,Our World in Data
1,year,Year of observation,Our World in Data
2,iso_code,ISO 3166-1 alpha-3 three-letter country codes,International Organization for Standardization
3,population,Population,Calculated by Our World in Data based on diffe...
4,gdp,"Total real gross domestic product, inflation-a...",Maddison Project Database
5,biofuel_cons_change_pct,Annual percentage change in biofuel consumption,Calculated by Our World in Data based on BP St...
6,biofuel_cons_change_twh,"Annual change in biofuel consumption, measured...",Calculated by Our World in Data based on BP St...
7,biofuel_cons_per_capita,Per capita primary energy consumption from bio...,Calculated by Our World in Data based on BP St...
8,biofuel_consumption,"Primary energy consumption from biofuels, meas...",Calculated by Our World in Data based on BP St...
9,biofuel_elec_per_capita,Per capita electricity generation from biofuel...,Calculated by Our World in Data based on BP St...
10,biofuel_electricity,"Electricity generation from biofuels, measured...",Calculated by Our World in Data based on BP St...
11,biofuel_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
12,biofuel_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
13,carbon_intensity_elec,"Carbon intensity of electricity production, me...",Calculated by Our World in Data based on BP St...
14,coal_cons_change_pct,Annual percentage change in coal consumption,Calculated by Our World in Data based on BP St...
15,coal_cons_change_twh,"Annual change in coal consumption, measured in...",Calculated by Our World in Data based on BP St...
16,coal_cons_per_capita,Per capita primary energy consumption from coa...,Calculated by Our World in Data based on BP St...
17,coal_consumption,"Primary energy consumption from coal, measured...",Calculated by Our World in Data based on BP St...
18,coal_elec_per_capita,"Per capita electricity generation from coal, m...",Calculated by Our World in Data based on BP St...
19,coal_electricity,"Electricity generation from coal, measured in ...",Calculated by Our World in Data based on BP St...
20,coal_prod_change_pct,Annual percentage change in coal production,Calculated by Our World in Data based on BP St...
21,coal_prod_change_twh,"Annual change in coal production, measured in ...",Calculated by Our World in Data based on BP St...
22,coal_prod_per_capita,"Per capita coal production, measured in kilowa...",Calculated by Our World in Data based on BP St...
23,coal_production,"Coal production, measured in terawatt-hours",Calculated by Our World in Data based on BP St...
24,coal_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
25,coal_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
26,electricity_demand,"Electricity demand, measured in terawatt-hours",Calculated by Our World in Data based on BP St...
27,electricity_generation,"Electricity generation, measured in terawatt-h...",Calculated by Our World in Data based on BP St...
28,energy_cons_change_pct,Annual percentage change in primary energy con...,Calculated by Our World in Data based on BP St...
29,energy_cons_change_twh,"Annual change in primary energy consumption, m...",Calculated by Our World in Data based on BP St...
30,energy_per_capita,"Primary energy consumption per capita, measure...",Calculated by Our World in Data based on BP St...
31,energy_per_gdp,Energy consumption per unit of GDP. This is me...,Calculated by Our World in Data based on BP St...
32,fossil_cons_change_pct,Annual percentage change in fossil fuel consum...,Calculated by Our World in Data based on BP St...
33,fossil_cons_change_twh,"Annual change in fossil fuel consumption, meas...",Calculated by Our World in Data based on BP St...
34,fossil_elec_per_capita,Per capita electricity generation from fossil ...,Calculated by Our World in Data based on BP St...
35,fossil_electricity,"Electricity generation from fossil fuels, meas...",Calculated by Our World in Data based on BP St...
36,fossil_energy_per_capita,"Per capita fossil fuel consumption, measured i...",Calculated by Our World in Data based on BP St...
37,fossil_fuel_consumption,"Fossil fuel consumption, measured in terawatt-...",Calculated by Our World in Data based on BP St...
38,fossil_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
39,fossil_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
40,gas_cons_change_pct,Annual percentage change in gas consumption,Calculated by Our World in Data based on BP St...
41,gas_cons_change_twh,"Annual change in gas consumption, measured in ...",Calculated by Our World in Data based on BP St...
42,gas_consumption,"Primary energy consumption from gas, measured ...",Calculated by Our World in Data based on BP St...
43,gas_elec_per_capita,"Per capita electricity generation from gas, me...",Calculated by Our World in Data based on BP St...
44,gas_electricity,"Electricity generation from gas, measured in t...",Calculated by Our World in Data based on BP St...
45,gas_energy_per_capita,Per capita primary energy consumption from gas...,Calculated by Our World in Data based on BP St...
46,gas_prod_change_pct,Annual percentage change in gas production,Calculated by Our World in Data based on BP St...
47,gas_prod_change_twh,"Annual change in gas production, measured in t...",Calculated by Our World in Data based on BP St...
48,gas_prod_per_capita,"Per capita gas production, measured in kilowat...",Calculated by Our World in Data based on BP St...
49,gas_production,"Gas production, measured in terawatt-hours",Calculated by Our World in Data based on BP St...
50,gas_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
51,gas_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
52,greenhouse_gas_emissions,Greenhouse-gas emissions produced in the gener...,Calculated by Our World in Data based on BP St...
53,hydro_cons_change_pct,Annual percentage change in hydropower consump...,Calculated by Our World in Data based on BP St...
54,hydro_cons_change_twh,"Annual change in hydropower consumption, measu...",Calculated by Our World in Data based on BP St...
55,hydro_consumption,"Primary energy consumption from hydropower, me...",Calculated by Our World in Data based on BP St...
56,hydro_elec_per_capita,Per capita electricity generation from hydropo...,Calculated by Our World in Data based on BP St...
57,hydro_electricity,"Electricity generation from hydropower, measur...",Calculated by Our World in Data based on BP St...
58,hydro_energy_per_capita,Per capita primary energy consumption from hyd...,Calculated by Our World in Data based on BP St...
59,hydro_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
60,hydro_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
61,low_carbon_cons_change_pct,Annual percentage change in low-carbon energy ...,Calculated by Our World in Data based on BP St...
62,low_carbon_cons_change_twh,Annual change in low-carbon energy consumption...,Calculated by Our World in Data based on BP St...
63,low_carbon_consumption,Primary energy consumption from low-carbon sou...,Calculated by Our World in Data based on BP St...
64,low_carbon_elec_per_capita,Per capita electricity generation from low-car...,Calculated by Our World in Data based on BP St...
65,low_carbon_electricity,Electricity generation from low-carbon sources...,Calculated by Our World in Data based on BP St...
66,low_carbon_energy_per_capita,Per capita primary energy consumption from low...,Calculated by Our World in Data based on BP St...
67,low_carbon_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
68,low_carbon_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
69,net_elec_imports,"Net electricity imports, measured in terawatt-...",Calculated by Our World in Data based on BP St...
70,net_elec_imports_share_demand,Net electricity imports as a share of electric...,Calculated by Our World in Data based on BP St...
71,nuclear_cons_change_pct,Annual percentage change in nuclear consumption,Calculated by Our World in Data based on BP St...
72,nuclear_cons_change_twh,"Annual change in nuclear consumption, measured...",Calculated by Our World in Data based on BP St...
73,nuclear_consumption,"Primary energy consumption from nuclear power,...",Calculated by Our World in Data based on BP St...
74,nuclear_elec_per_capita,Per capita electricity generation from nuclear...,Calculated by Our World in Data based on BP St...
75,nuclear_electricity,"Electricity generation from nuclear power, mea...",Calculated by Our World in Data based on BP St...
76,nuclear_energy_per_capita,Per capita primary energy consumption from nuc...,Calculated by Our World in Data based on BP St...
77,nuclear_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
78,nuclear_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
79,oil_cons_change_pct,Annual percentage change in oil consumption,Calculated by Our World in Data based on BP St...
80,oil_cons_change_twh,"Annual change in oil consumption, measured in ...",Calculated by Our World in Data based on BP St...
81,oil_consumption,"Primary energy consumption from oil, measured ...",Calculated by Our World in Data based on BP St...
82,oil_elec_per_capita,"Per capita electricity generation from oil, me...",Calculated by Our World in Data based on BP St...
83,oil_electricity,"Electricity generation from oil, measured in t...",Calculated by Our World in Data based on BP St...
84,oil_energy_per_capita,Per capita primary energy consumption from oil...,Calculated by Our World in Data based on BP St...
85,oil_prod_change_pct,Annual percentage change in oil production,Calculated by Our World in Data based on BP St...
86,oil_prod_change_twh,"Annual change in oil production, measured in t...",Calculated by Our World in Data based on BP St...
87,oil_prod_per_capita,"Per capita oil production, measured in kilowat...",Calculated by Our World in Data based on BP St...
88,oil_production,"Oil production, measured in terawatt-hours",Calculated by Our World in Data based on BP St...
89,oil_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
90,oil_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
91,other_renewable_consumption,Primary energy consumption from other renewabl...,Calculated by Our World in Data based on BP St...
92,other_renewable_electricity,Electricity generation from other renewable so...,Calculated by Our World in Data based on BP St...
93,other_renewable_exc_biofuel_electricity,Electricity generation from other renewable so...,Calculated by Our World in Data based on BP St...
94,other_renewables_cons_change_pct,Annual percentage change in energy consumption...,Calculated by Our World in Data based on BP St...
95,other_renewables_cons_change_twh,"Annual change in other renewable consumption, ...",Calculated by Our World in Data based on BP St...
96,other_renewables_elec_per_capita,Per capita electricity generation from other r...,Calculated by Our World in Data based on BP St...
97,other_renewables_elec_per_capita_exc_biofuel,Per capita electricity generation from other r...,Calculated by Our World in Data based on BP St...
98,other_renewables_energy_per_capita,Per capita primary energy consumption from oth...,Calculated by Our World in Data based on BP St...
99,other_renewables_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
100,other_renewables_share_elec_exc_biofuel,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
101,other_renewables_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
102,per_capita_electricity,"Electricity generation per capita, measured in...",Calculated by Our World in Data based on BP St...
103,primary_energy_consumption,"Primary energy consumption, measured in terawa...",Calculated by Our World in Data based on BP St...
104,renewables_cons_change_pct,Annual percentage change in renewable energy c...,Calculated by Our World in Data based on BP St...
105,renewables_cons_change_twh,"Annual change in renewable energy consumption,...",Calculated by Our World in Data based on BP St...
106,renewables_consumption,"Primary energy consumption from renewables, me...",Calculated by Our World in Data based on BP St...
107,renewables_elec_per_capita,Per capita electricity generation from renewab...,Calculated by Our World in Data based on BP St...
108,renewables_electricity,"Electricity generation from renewables, measur...",Calculated by Our World in Data based on BP St...
109,renewables_energy_per_capita,Per capita primary energy consumption from ren...,Calculated by Our World in Data based on BP St...
110,renewables_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
111,renewables_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
112,solar_cons_change_pct,Annual percentage change in solar consumption,Calculated by Our World in Data based on BP St...
113,solar_cons_change_twh,"Annual change in solar consumption, measured i...",Calculated by Our World in Data based on BP St...
114,solar_consumption,"Primary energy consumption from solar, measure...",Calculated by Our World in Data based on BP St...
115,solar_elec_per_capita,"Per capita electricity generation from solar, ...",Calculated by Our World in Data based on BP St...
116,solar_electricity,"Electricity generation from solar, measured in...",Calculated by Our World in Data based on BP St...
117,solar_energy_per_capita,Per capita primary energy consumption from sol...,Calculated by Our World in Data based on BP St...
118,solar_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
119,solar_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...
120,wind_cons_change_pct,Annual percentage change in wind consumption,Calculated by Our World in Data based on BP St...
121,wind_cons_change_twh,"Annual change in wind consumption, measured in...",Calculated by Our World in Data based on BP St...
122,wind_consumption,"Primary energy consumption from wind, measured...",Calculated by Our World in Data based on BP St...
123,wind_elec_per_capita,"Per capita electricity generation from wind, m...",Calculated by Our World in Data based on BP St...
124,wind_electricity,"Electricity generation from wind, measured in ...",Calculated by Our World in Data based on BP St...
125,wind_energy_per_capita,Per capita primary energy consumption from win...,Calculated by Our World in Data based on BP St...
126,wind_share_elec,Share of electricity generation that comes fro...,Calculated by Our World in Data based on BP St...
127,wind_share_energy,Share of primary energy consumption that comes...,Calculated by Our World in Data based on BP St...

## Filter data by year and country

In [13]:
list_countries_from_df = df['country'].unique().tolist()

In [14]:
list_countries_from_df

['Afghanistan',
 'Africa',
 'Africa (BP)',
 'Africa (Shift)',
 'Albania',
 'Algeria',
 'American Samoa',
 'Angola',
 'Antarctica',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Asia',
 'Asia & Oceania (EIA)',
 'Asia Pacific (BP)',
 'Asia and Oceania (Shift)',
 'Australia',
 'Australia and New Zealand (EIA)',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'CIS (BP)',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central & South America (EIA)',
 'Central African Republic',
 'Central America (BP)',
 'Central and South America (Shift)',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Cyprus',
 'Czechia',
 'Czechoslovakia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'EU28 (Shift)',
 'East Germany (EIA)',
 'Eastern Africa (BP)',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Eurasia (EIA)',
 'Eurasia (Shift)',
 'Europe',
 'Europe (BP)',
 'Europe (Shift)',
 'European Union (27)',
 'European Union (EIA)',
 'Faeroe Islands',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'G20 (Ember)',
 'G7 (Ember)',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'Hawaiian Trade Zone (EIA)',
 'High-income countries',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'IEO - Africa (EIA)',
 'IEO - Middle East (EIA)',
 'IEO OECD - Europe (EIA)',
 'Iceland',
 'Inde (Shift)',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latin America and Caribbean (Ember)',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Lithuania',
 'Low-income countries',
 'Lower-middle-income countries',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mexico',
 'Mexico, Chile, and other OECD Americas (EIA)',
 'Micronesia (country)',
 'Middle Africa (BP)',
 'Middle East (BP)',
 'Middle East (EIA)',
 'Middle East (Ember)',
 'Middle East (Shift)',
 'Moldova',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'Netherlands Antilles',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'Non-OECD (BP)',
 'Non-OECD (EIA)',
 'Non-OPEC (EIA)',
 'North America',
 'North America (BP)',
 'North America (Shift)',
 'North Korea',
 'North Macedonia',
 'Northern Mariana Islands',
 'Norway',
 'OECD (BP)',
 'OECD (EIA)',
 'OECD (Ember)',
 'OECD (Shift)',
 'OECD - Asia And Oceania (EIA)',
 'OECD - Europe (EIA)',
 'OECD - North America (EIA)',
 'OPEC (EIA)',
 'OPEC (Shift)',
 'OPEC - Africa (EIA)',
 'OPEC - South America (EIA)',
 'Oceania',
 'Oman',
 'Other Africa (BP)',
 'Other Asia Pacific (BP)',
 'Other CIS (BP)',
 'Other Caribbean (BP)',
 'Other Eastern Africa (BP)',
 'Other Europe (BP)',
 'Other Middle Africa (BP)',
 'Other Middle East (BP)',
 'Other Non-OECD - America (EIA)',
 'Other Non-OECD - Asia (EIA)',
 'Other Non-OECD - Europe and Eurasia (EIA)',
 'Other Northern Africa (BP)',
 'Other South America (BP)',
 'Other South and Central America (BP)',
 'Other Southern Africa (BP)',
 'Other Western Africa (BP)',
 'Pakistan',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Persian Gulf (EIA)',
 'Persian Gulf (Shift)',
 'Peru',
 'Philippines',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Senegal',
 'Serbia',
 'Serbia and Montenegro',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South America',
 'South Korea',
 'South Korea and other OECD Asia (EIA)',
 'South Sudan',
 'South and Central America (BP)',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor',
 'Togo',
 'Tonga',
 'Total Non-OPEC (BP)',
 'Total OPEC (BP)',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'U.S. Pacific Islands (EIA)',
 'U.S. Pacific Islands (Shift)',
 'U.S. Territories (EIA)',
 'U.S. Territories (Shift)',
 'USSR',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Upper-middle-income countries',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Venezuela',
 'Vietnam',
 'Wake Island (EIA)',
 'Wake Island (Shift)',
 'West Germany (EIA)',
 'Western Africa (BP)',
 'Western Sahara',
 'World',
 'Yemen',
 'Yugoslavia',
 'Zambia',
 'Zimbabwe']

Keep only countries from next list (from [GitHub](https://gist.githubusercontent.com/kalinchernev/486393efcca01623b18d/raw/daa24c9fea66afb7d68f8d69f0c4b8eeb9406e83/countries) + add countries with other name):

In [15]:
countries = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua & Deps',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina',
    'Burundi',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Cape Verde',
    'Central African Rep',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Congo {Democratic Rep}',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'East Timor',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland {Republic}',
    'Israel',
    'Italy',
    'Ivory Coast',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Korea North',
    'Korea South',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macedonia',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar, {Burma}',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'St Kitts & Nevis',
    'St Lucia',
    'Saint Vincent & the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome & Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Togo',
    'Tonga',
    'Trinidad & Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
    'Myanmar',
    'Bosnia and Herzegovina',
    'Czechia',
    'Democratic Republic of Congo',
    'Faeroe Islands',
    'Falkland Islands',
    'Ireland',
    'Mexico',
    'Russia',
    'Western Sahara',
    'Chile',
    'Central African Republic',
    'South Korea',
    'North Korea',
    'North Macedonia'
]

In [16]:
print (set(list_countries_from_df) - set(countries))

{'Central & South America (EIA)', 'Other Middle Africa (BP)', 'Oceania', 'OPEC (Shift)', 'U.S. Territories (EIA)', 'North America (Shift)', 'Africa (Shift)', 'Palestine', 'U.S. Territories (Shift)', 'Asia & Oceania (EIA)', 'G7 (Ember)', 'Saint Kitts and Nevis', 'World', 'Other Non-OECD - America (EIA)', 'OECD (BP)', 'Serbia and Montenegro', 'CIS (BP)', "Cote d'Ivoire", 'Saint Helena', 'Yugoslavia', 'Guam', 'Middle East (EIA)', 'Martinique', 'Montserrat', 'Total OPEC (BP)', 'Other Caribbean (BP)', 'Upper-middle-income countries', 'Non-OECD (BP)', 'Other Europe (BP)', 'Other South America (BP)', 'Eurasia (Shift)', 'New Caledonia', 'U.S. Pacific Islands (Shift)', 'European Union (EIA)', 'G20 (Ember)', 'Micronesia (country)', 'OPEC - Africa (EIA)', 'Total Non-OPEC (BP)', 'Middle East (BP)', 'Latin America and Caribbean (Ember)', 'Greenland', 'Europe', 'OECD (EIA)', 'OECD - North America (EIA)', 'Persian Gulf (EIA)', 'Saint Lucia', 'Sao Tome and Principe', 'OECD (Shift)', 'South Korea and other OECD Asia (EIA)', 'United States Virgin Islands', 'Middle East (Ember)', 'Niue', 'U.S. Pacific Islands (EIA)', 'Other Middle East (BP)', 'Europe (Shift)', 'Hong Kong', 'IEO - Middle East (EIA)', 'Non-OPEC (EIA)', 'Eastern Africa (BP)', 'Middle Africa (BP)', 'Other CIS (BP)', 'Asia Pacific (BP)', 'Burkina Faso', 'Antarctica', 'Other Northern Africa (BP)', 'Wake Island (Shift)', 'Czechoslovakia', 'Europe (BP)', 'OECD - Europe (EIA)', 'Bermuda', 'Macao', 'Guadeloupe', 'North America (BP)', 'Saint Pierre and Miquelon', 'Inde (Shift)', 'American Samoa', 'IEO - Africa (EIA)', 'High-income countries', 'Antigua and Barbuda', 'Mexico, Chile, and other OECD Americas (EIA)', 'Aruba', 'Netherlands Antilles', 'West Germany (EIA)', 'Other Asia Pacific (BP)', 'Africa (BP)', 'Other Southern Africa (BP)', 'Puerto Rico', 'Reunion', 'Timor', 'OECD - Asia And Oceania (EIA)', 'Australia and New Zealand (EIA)', 'North America', 'Wake Island (EIA)', 'French Guiana', 'Asia', 'South America', 'Other Non-OECD - Asia (EIA)', 'Other Western Africa (BP)', 'European Union (27)', 'Middle East (Shift)', 'Africa', 'Non-OECD (EIA)', 'Eswatini', 'OPEC - South America (EIA)', 'OPEC (EIA)', 'Gibraltar', 'Eurasia (EIA)', 'Northern Mariana Islands', 'Turks and Caicos Islands', 'Cayman Islands', 'Other Eastern Africa (BP)', 'South and Central America (BP)', 'Other South and Central America (BP)', 'Saint Vincent and the Grenadines', 'OECD (Ember)', 'Asia and Oceania (Shift)', 'Trinidad and Tobago', 'Central America (BP)', 'Cook Islands', 'French Polynesia', 'IEO OECD - Europe (EIA)', 'Western Africa (BP)', 'Other Non-OECD - Europe and Eurasia (EIA)', 'Low-income countries', 'British Virgin Islands', 'East Germany (EIA)', 'EU28 (Shift)', 'USSR', 'Persian Gulf (Shift)', 'Other Africa (BP)', 'Hawaiian Trade Zone (EIA)', 'Lower-middle-income countries', 'Central and South America (Shift)'}

In [17]:
df = df[df['country'].isin(countries)]

In [18]:
df = df[df['year']>1999]

In [19]:
df.head()

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
100,Afghanistan,2000,AFG,20779958.0,1.128379e+10,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
101,Afghanistan,2001,AFG,21606992.0,1.102127e+10,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
102,Afghanistan,2002,AFG,22600774.0,1.880487e+10,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
103,Afghanistan,2003,AFG,23680872.0,2.107434e+10,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
104,Afghanistan,2004,AFG,24726690.0,2.233257e+10,NaN,NaN,NaN,NaN,0.0,...,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN

## Create dataframe with general info about country

In [20]:
df_country = df[['iso_code', 
               'country', 
               'year',
               'population',
               'gdp',
               'carbon_intensity_elec'
              ]]

In [22]:
df_country.to_csv('owid-energy-data-countries.csv',index=False,sep=';')

## Create dataframe with general info about electricity production

In [24]:
df.loc[(df['country'] == 'Egypt') & (df['year'] == 2020)]

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,...,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
5926,Egypt,2020,EGY,102334408.0,NaN,NaN,NaN,NaN,NaN,0.0,...,1.428,0.757,37.552,4.862,17.986,66.921,6.848,175.754,3.448,1.828

In [25]:
df = df[['iso_code', 
         'year',
         'biofuel_electricity', 
         'hydro_electricity',
         'nuclear_electricity',
         'solar_electricity',
         'wind_electricity', 
         'coal_electricity',
         'gas_electricity',
         'oil_electricity',
          ]]

df

,iso_code,year,biofuel_electricity,hydro_electricity,nuclear_electricity,solar_electricity,wind_electricity,coal_electricity,gas_electricity,oil_electricity
100,AFG,2000,0.00,0.31,0.0,0.00,0.0,0.00,0.0,0.16
101,AFG,2001,0.00,0.50,0.0,0.00,0.0,0.00,0.0,0.09
102,AFG,2002,0.00,0.56,0.0,0.00,0.0,0.00,0.0,0.13
103,AFG,2003,0.00,0.63,0.0,0.00,0.0,0.00,0.0,0.31
104,AFG,2004,0.00,0.56,0.0,0.00,0.0,0.00,0.0,0.33
...,...,...,...,...,...,...,...,...,...,...
22338,ZWE,2017,0.32,3.93,0.0,0.01,0.0,3.02,0.0,0.03
22339,ZWE,2018,0.39,5.00,0.0,0.01,0.0,3.69,0.0,0.04
22340,ZWE,2019,0.38,7.26,0.0,0.01,0.0,3.62,0.0,0.04
22341,ZWE,2020,0.36,7.26,0.0,0.01,0.0,3.44,0.0,0.04
22342,ZWE,2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
df.loc[(df['iso_code'] == 'EGY') & (df['year'] == 2020)]

,iso_code,year,biofuel_electricity,hydro_electricity,nuclear_electricity,solar_electricity,wind_electricity,coal_electricity,gas_electricity,oil_electricity
5926,EGY,2020,0.0,14.903,0.0,2.837,6.848,0.0,151.284,22.738

In [28]:
df_energy = df.melt(id_vars=['iso_code', 'year'],
                    var_name='fuel',
                    value_name='production'
)

df_energy

      iso_code  year                 fuel  production
0          AFG  2000  biofuel_electricity        0.00
1          AFG  2001  biofuel_electricity        0.00
2          AFG  2002  biofuel_electricity        0.00
3          AFG  2003  biofuel_electricity        0.00
4          AFG  2004  biofuel_electricity        0.00
...        ...   ...                  ...         ...
31131      ZWE  2017      oil_electricity        0.03
31132      ZWE  2018      oil_electricity        0.04
31133      ZWE  2019      oil_electricity        0.04
31134      ZWE  2020      oil_electricity        0.04
31135      ZWE  2021      oil_electricity         NaN

[31136 rows x 4 columns]

In [29]:
df_energy.loc[(df_energy['iso_code'] == 'EGY') & (df_energy['year'] == 2020)]

      iso_code  year                 fuel  production
1036       EGY  2020  biofuel_electricity       0.000
4928       EGY  2020    hydro_electricity      14.903
8820       EGY  2020  nuclear_electricity       0.000
12712      EGY  2020    solar_electricity       2.837
16604      EGY  2020     wind_electricity       6.848
20496      EGY  2020     coal_electricity       0.000
24388      EGY  2020      gas_electricity     151.284
28280      EGY  2020      oil_electricity      22.738

In [31]:
df_energy['fuel'] = df_energy['fuel'].str.replace('_electricity', '')

df_energy['fuel'].unique()

array(['biofuel', 'hydro', 'nuclear', 'solar', 'wind', 'coal', 'gas',
       'oil'], dtype=object)

In [32]:
df_energy.loc[(df_energy['iso_code'] == 'EGY') & (df_energy['year'] == 2020)]

      iso_code  year     fuel  production
1036       EGY  2020  biofuel       0.000
4928       EGY  2020    hydro      14.903
8820       EGY  2020  nuclear       0.000
12712      EGY  2020    solar       2.837
16604      EGY  2020     wind       6.848
20496      EGY  2020     coal       0.000
24388      EGY  2020      gas     151.284
28280      EGY  2020      oil      22.738

In [33]:
df_energy.to_csv('owid-energy-data-energy.csv',index=False,sep=';')